name: permuformer
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - pytorch-cuda=11.8
  - pip
  - pip:
    - wandb
    - transformers
    - datasets
    - nltk
    - sentencepiece
    - sacremoses
    - torch-optimizer

# conda install numpy pandas matplotlib seaborn scikit-learn jupyter notebook tqdm